# Generated by Django 2.2.8 on 2020-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='avatar',
            field=models.TextField(default='default_avatar.png', max_length=100),
        ),
    ]
