# Generated by Django 2.2.8 on 2020-11-16 17:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_auto_20201116_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='occupy',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='occupy',
        ),
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2020, 11, 16, 17, 25, 56, 49249), editable=False, verbose_name='زمان ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2020, 11, 16, 17, 26, 6, 754172), editable=False, verbose_name='آخرین زمان تغییر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
