# Generated by Django 2.2.8 on 2020-11-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_auto_20201116_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': 'اکانت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccount',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical اکانت'},
        ),
    ]
