# Generated by Django 2.2.8 on 2020-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0004_auto_20201117_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تماس '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, verbose_name='شماره تماس '),
            preserve_default=False,
        ),
    ]
