# Generated by Django 2.2.8 on 2020-11-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0005_auto_20201120_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس '),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس '),
        ),
    ]
