# Generated by Django 2.2.8 on 2020-11-16 17:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('dog', 'سگ'), ('cat', 'گربه'), ('hamster', 'همستر')], db_index=True, default='dog', max_length=20, verbose_name='نوع حیوان خانگی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('pet_image', models.ImageField(blank=True, upload_to='', verbose_name='تصویر')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست',
                'db_table': 'animals_post',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='adoption.Post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'db_table': 'animals_comment',
                'verbose_name_plural': 'کامنت\u200cها',
            },
        ),
    ]
