# Generated by Django 2.2.8 on 2020-11-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_auto_20201117_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
